2021-12-28 07:52:57 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'd1d7f39a-f06b-4ec9-9d44-e8fe9b0cdad5'  [42102-200]
2021-12-28 07:52:57 jdbc[20]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'e2d32be7-3554-4a48-bb0f-c2dd166a3e5d'  [42102-200]
2021-12-28 07:52:57 jdbc[25]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '1bf9a7cd-d382-4d39-b3e6-73e7fed42e8f'  [42102-200]
2021-12-28 07:52:58 jdbc[29]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f0a8563-9362-4b1a-b19a-6c0559b7147d'  [42102-200]
2021-12-28 07:52:58 jdbc[30]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '66d07b0a-ee5f-43e1-ae0a-e3d142255d8c'  [42102-200]
2021-12-28 07:52:58 jdbc[31]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'fab6a6a7-4c20-47c7-a46b-c6b28498f860'  [42102-200]
2021-12-28 07:52:58 jdbc[32]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'dc6507cc-8321-4b70-bd17-d552a4c1d2f0'  [42102-200]
2021-12-28 07:52:58 jdbc[33]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '2b0ca557-b952-4b09-a114-7136cec61d57'  [42102-200]
2021-12-28 07:52:58 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '6350b33e-795e-40e2-8192-501dfe715c02'  [42102-200]
2021-12-28 07:52:58 jdbc[35]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '7585125a-8cbd-4cb3-924b-3b745931e22f'  [42102-200]
2021-12-28 07:52:58 jdbc[36]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '29c15591-299a-4e67-8f38-be3e81302ca6'  [42102-200]
2021-12-28 07:52:58 jdbc[37]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f0a8563-9362-4b1a-b19a-6c0559b7147d'  [42102-200]
2021-12-28 07:52:58 jdbc[38]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '66d07b0a-ee5f-43e1-ae0a-e3d142255d8c'  [42102-200]
2021-12-28 07:52:58 jdbc[39]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'fab6a6a7-4c20-47c7-a46b-c6b28498f860'  [42102-200]
2021-12-28 07:52:58 jdbc[40]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'dc6507cc-8321-4b70-bd17-d552a4c1d2f0'  [42102-200]
2021-12-28 07:52:58 jdbc[41]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '2b0ca557-b952-4b09-a114-7136cec61d57'  [42102-200]
2021-12-28 07:52:58 jdbc[42]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '6350b33e-795e-40e2-8192-501dfe715c02'  [42102-200]
2021-12-28 07:52:58 jdbc[43]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '7585125a-8cbd-4cb3-924b-3b745931e22f'  [42102-200]
2021-12-28 07:52:58 jdbc[44]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '29c15591-299a-4e67-8f38-be3e81302ca6'  [42102-200]
2021-12-28 07:52:58 jdbc[45]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
DELETE FROM ACTION  [42102-200]
2021-12-28 07:52:58 jdbc[52]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '62f2f4f1-4c9d-4e69-b957-419689012ecf'  [42102-200]
2021-12-28 07:52:58 jdbc[53]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'eab2a731-085c-4488-8602-13a6655e0c11'  [42102-200]
2021-12-28 07:52:58 jdbc[58]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'e4381906-2734-4c34-823d-a1b3007af2a3'  [42102-200]
2021-12-28 07:52:58 jdbc[59]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'e4381906-2734-4c34-823d-a1b3007af2a3'  [42102-200]
2021-12-28 07:52:58 jdbc[63]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'a0f91240-73a8-4675-9ded-59187c2078bf'  [42102-200]
2021-12-28 07:52:58 jdbc[64]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '1d94623a-025e-4d37-9514-2dfbbd383d2b'  [42102-200]
2021-12-28 07:52:58 jdbc[65]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '025758aa-637e-46e6-8d64-4ecbf167a44f'  [42102-200]
2021-12-28 07:52:58 jdbc[66]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '40cb24b1-96e8-4022-af2c-7d14d3521dbb'  [42102-200]
2021-12-28 07:52:58 jdbc[67]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'cdf257c3-0101-4f39-9d73-dac6938050f8'  [42102-200]
2021-12-28 07:52:58 jdbc[68]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'caee18f3-76e6-481e-b524-2d4bc7cbe95b'  [42102-200]
2021-12-28 07:52:58 jdbc[69]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '87992757-066a-4fba-9ed9-3dda3c538561'  [42102-200]
2021-12-28 07:52:58 jdbc[70]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'c90cf4a8-c6c0-4c15-89c1-9c27cd1f616e'  [42102-200]
2021-12-28 07:53:00 jdbc[11]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '9dd284a0-be8c-4ec6-b6b9-d8f9230a7353'  [42102-200]
2021-12-28 07:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '6b11dbca-8268-46f9-8bc0-540a88c547d0'  [42102-200]
2021-12-28 07:53:02 jdbc[24]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'f05411a4-be53-4699-82db-7362dde52e59'  [42102-200]
2021-12-28 07:53:02 jdbc[25]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '2f363f2a-16b4-4935-9558-519cd10fcf83'  [42102-200]
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.resultSetToStock(DataProviderJdbc.java:552)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:250)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.setHistory(DataProviderJdbc.java:225)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:256)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.resultSetToStock(DataProviderJdbc.java:552)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:250)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.resultSetToStock(DataProviderJdbc.java:552)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:250)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.setHistory(DataProviderJdbc.java:225)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:256)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.setHistory(DataProviderJdbc.java:225)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:256)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.setHistory(DataProviderJdbc.java:225)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:256)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.resultSetToStock(DataProviderJdbc.java:552)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:250)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:245)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.setHistory(DataProviderJdbc.java:225)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:256)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[36]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:834)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryByDate(DataProviderJdbc.java:848)
	at ru.sfedu.api.DataProviderJdbc.resultSetToStock(DataProviderJdbc.java:552)
	at ru.sfedu.api.DataProviderJdbc.getSecurities(DataProviderJdbc.java:250)
	at ru.sfedu.api.DataProviderJdbc.getStocks(DataProviderJdbc.java:598)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:460)
	at ru.sfedu.api.DataProviderJdbc.getStocksByTickerList(DataProviderJdbc.java:663)
	at ru.sfedu.api.DataProviderJdbc.getSecuritiesByTickerList(DataProviderJdbc.java:683)
	at ru.sfedu.api.DataProviderJdbc.getUsersSecurity(DataProviderJdbc.java:1341)
	at ru.sfedu.api.DataProviderJdbc.resultSetToUser(DataProviderJdbc.java:921)
	at ru.sfedu.api.DataProviderJdbc.getUserById(DataProviderJdbc.java:1083)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1172)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.appendAction(DataProviderJdbc.java:1186)
	at ru.sfedu.api.DataProviderJdbcTest.testDeleteActionHistory(DataProviderJdbcTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
2021-12-28 07:53:02 jdbc[56]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'b67227a8-e893-4437-ac51-c2aaa1bd454f'  [42102-200]
2021-12-28 07:53:02 jdbc[64]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f1b9091-2136-483f-925d-927579111c36'  [42102-200]
2021-12-28 07:53:02 jdbc[65]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f1b9091-2136-483f-925d-927579111c36'  [42102-200]
2021-12-28 07:53:02 jdbc[66]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f1b9091-2136-483f-925d-927579111c36'  [42102-200]
2021-12-28 07:53:03 jdbc[78]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '4037f06f-9592-49d1-87f2-96490aaacbf6'  [42102-200]
2021-12-28 07:53:03 jdbc[77]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
DELETE FROM ACTION WHERE user_id = '4037f06f-9592-49d1-87f2-96490aaacbf6'  [42102-200]
2021-12-28 07:53:03 jdbc[79]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '4037f06f-9592-49d1-87f2-96490aaacbf6'  [42102-200]
2021-12-28 07:53:03 jdbc[80]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '4037f06f-9592-49d1-87f2-96490aaacbf6'  [42102-200]
2021-12-28 07:53:03 jdbc[86]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'dwads'  [42102-200]
2021-12-28 07:53:03 jdbc[85]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
DELETE FROM ACTION WHERE user_id = 'dwads'  [42102-200]
2021-12-28 07:53:03 jdbc[87]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '33d9e099-9837-4a05-ab43-981fe93ccdc0'  [42102-200]
2021-12-28 07:53:03 jdbc[94]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '367c793b-d533-434c-9380-c93278a15234'  [42102-200]
2021-12-28 07:53:03 jdbc[98]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '1582a8d9-503f-4efe-b1db-d7f8445f1858'  [42102-200]
2021-12-28 07:53:03 jdbc[99]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '1582a8d9-503f-4efe-b1db-d7f8445f1858'  [42102-200]
2021-12-28 07:53:03 jdbc[100]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '1582a8d9-503f-4efe-b1db-d7f8445f1858'  [42102-200]
2021-12-28 07:53:03 jdbc[126]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'fa501b1c-7019-43c8-86ba-95c0ea95bc85'  [42102-200]
2021-12-28 07:53:03 jdbc[127]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '3c7e4b05-b92b-48c4-9b1a-bd266970fe8c'  [42102-200]
2021-12-28 07:53:03 jdbc[128]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '19ebbc7f-2ef9-4f49-a509-f355eb44bc08'  [42102-200]
2021-12-28 07:53:03 jdbc[129]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '0f2fd595-806f-41d9-9f58-089f2eea2a3f'  [42102-200]
2021-12-28 07:53:03 jdbc[130]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '2330133e-43da-4cb0-b64f-79c3bd62bbd9'  [42102-200]
2021-12-28 07:53:03 jdbc[131]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'd2601b38-a742-4aa3-95e0-b8720e459895'  [42102-200]
2021-12-28 07:53:03 jdbc[132]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = 'd2183ef5-d73b-41aa-a072-0f46879480c2'  [42102-200]
2021-12-28 07:53:03 jdbc[133]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '868ccd81-3e29-4f0e-ba89-dd9876573daa'  [42102-200]
2021-12-28 07:53:03 jdbc[135]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '39ee2ffd-1f19-48f2-bf41-161dcf27a62d'  [42102-200]
2021-12-28 07:53:03 jdbc[136]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACTION" не найдена
Table "ACTION" not found; SQL statement:
SELECT * FROM ACTION WHERE user_id = '3a4eaee7-6fc8-44d4-84f2-0d77a33f216f'  [42102-200]
